# Generated by Django 3.1 on 2021-01-11 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('World', 'World'), ('Science', 'Science'), ('Sports', 'Sports'), ('Design', 'Design'), ('Culture', 'Culture'), ('Technology', 'Technology')], default='World', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('excerpt', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featred', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
